### PR TITLE
add clickhandler to support touch

### LINKED ISSUE #9: ClickOutside not working on iOS devices
I haven't done extensive testing on this, but in using the latest version of this package straight from GitHub, rather than npm, the events failed to fire on iOS for some reason. The only device I tried this on was an iPhone 7, though I'm unsure of the Safari version (I don't own an iOS device).

I found a workaround through a similar package for React—[kentor/react-click-outside](https://github.com/kentor/react-click-outside), where their README mentions needing `cursor: pointer` on the `document.body` for iOS to see the event here:
https://github.com/kentor/react-click-outside#not-working-on-ios

After I did this, `vue-click-outside` started working like a charm on a buddy's iPhone.

I'm not sure if this is something worth implementing in the package itself, or if it should be mentioned in the README since there are a number of ways to handle feature detection and adding this workaround.

Thanks!

### PR DESCRIPTION
**Pull request by pqt**
Fixes #9

### CODE REVIEW

**Comment by brennenf** [comment]
I'd like to second this merge request as it applies a simple fix for touchevents on iOS. Having it in master and NPM will make it possible to automate deployment routines without having to re-patch. Thanks for the consideration.

**Comment by OperKH** [comment]
I think this PR should be rewritten to ES5.

**Comment by AustinPaquette** [comment]
@OperKH any particular reason for that?

**Comment by fundon** [comment]
Need merge?

**Comment by trollepierre** [comment]
when will this PR be merged?

**Comment by AustinPaquette** [comment]
@fundon I think it's ready to be merged anytime, I'm on standby though if anything needs to be changed.

**Comment by pqt** [comment]
@fundon any update on this, would like to get it merged since it's a rather tiny change.

**Comment by trollepierre** [comment]
Last commit on this project was one year ago.
I believe this project is dead. Maybe it would be a good idea to create a new open source project containing this PR, and try to redirect user to this new repository ;-)

**Comment by pqt** [comment]
@trollepierre normally I would, but there's already identical options around. People using bulma probably would feel most comfortable with using the things all under the same roof.

For what it's worth, if someone want's this solution (without pulling this specific commit into the mix) then you can use [ndelvalle/v-click-outside](https://github.com/ndelvalle/v-click-outside).

[It has it already baked in](https://github.com/ndelvalle/v-click-outside/blob/master/lib/v-click-outside.js#L2)

https://github.com/ndelvalle/v-click-outside/blob/master/lib/v-click-outside.js#L2

**Comment by pqt** [comment]
Closes in favour of #17

**Pull request closed without merging**
